source('https://rubygems.org')

gem('sinatra')
gem('sinatra-contrib')
gem('rspec')
gem('capybara')
gem('pry')
gem('launchy')
gem('pg')
gem('sinatra-activerecord')
gem('rake')
gem('twitter')
gem('easy_translate')
gem('dotenv')
